name: Scan with synopsys action@v1.9.0

on:
  workflow_dispatch:

env:
  PROJECT_NAME: 'testactions'
  PROJECT_VERSION: '1.0'

jobs:
  sca:
    runs-on:
      labels: self-hosted
    container:
      # image: maven:3.9.5-eclipse-temurin-17-alpine
      image: maven:3.9.5-eclipse-temurin-17

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      # run: apk add unzip
      run: apt-get update && apt-get install -y unzip

    # - name: Print synopsys bridge directory
    #   run: |
    #     ls /github/home -la
    #     ls /github/home/synopsys-bridge -la
    #     ls /github/home/synopsys-bridge/extensions -la

    - name: SCA Scan
      uses: synopsys-sig/synopsys-action@v1.9.0

      env:
        DETECT_PROJECT_NAME: ${{ env.PROJECT_NAME }}
        DETECT_PROJECT_VERSION_NAME: ${{ env.PROJECT_VERSION }}
        DETECT_TOOLS: 'DETECTOR,SIGNATURE_SCAN'
        DETECT_DETECTOR_SEARCH_CONTINUE: 'true'
        DETECT_DETECTOR_SEARCH_DEPTH: '10000'
        DETECT_BLACKDUCK_SIGNATURE_SCANNER_SNIPPET_MATCHING: 'SNIPPET_MATCHING'
        DETECT_BLACKDUCK_SIGNATURE_SCANNER_UPLOAD_SOURCE_MODE: 'true'
        BLACKDUCK_TRUST_CERT: 'true'
      with:
        blackduck_url: ${{ secrets.BLACKDUCK_URL }}
        blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        blackduck_scan_full: true
        blackduck_reports_sarif_create: true
        blackduck_upload_sarif_report: true
        blackduck.automation.fixpr: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Pause for Debugging
      if: failure()
      run: sleep 1h
      continue-on-error: true
