name: Scan with synopsys action@v1.9.0 updated version 

on:
  workflow_dispatch:

env:
  PROJECT_NAME: 'testactions'
  PROJECT_VERSION: '1.0'

jobs:
  sca:
    runs-on:
      labels: self-hosted
    container:
      image: maven:3.9.5-eclipse-temurin-17

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: apt-get update && apt-get install -y unzip

    - name: Set Environment Variables
      run: |
        echo "DETECT_PROJECT_NAME=${{ env.PROJECT_NAME }}" >> $GITHUB_ENV
        echo "DETECT_PROJECT_VERSION_NAME=${{ env.PROJECT_VERSION }}" >> $GITHUB_ENV
        echo "DETECT_TOOLS=DETECTOR" >> $GITHUB_ENV
        echo "DETECT_DETECTOR_SEARCH_CONTINUE=true" >> $GITHUB_ENV
        echo "DETECT_DETECTOR_SEARCH_DEPTH=10000" >> $GITHUB_ENV
        echo "DETECT_BLACKDUCK_SIGNATURE_SCANNER_SNIPPET_MATCHING=SNIPPET_MATCHING" >> $GITHUB_ENV
        echo "DETECT_BLACKDUCK_SIGNATURE_SCANNER_UPLOAD_SOURCE_MODE=true" >> $GITHUB_ENV
        echo "BLACKDUCK_TRUST_CERT=true" >> $GITHUB_ENV

    - name: SCA Scan
      id: sca-scan
      run: |
        synopsys-sig/synopsys-action@v1.9.0 2>&1 | tee output.log
      env:
        blackduck_url: ${{ secrets.BLACKDUCK1_URL }}
        blackduck_token: ${{ secrets.BLACKDUCK1_API_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Check SCA Scan Result
      if: always()
      run: |
        if grep -q "File /__w/simple-java-maven-app/simple-java-maven-app/.bridge/Blackduck SARIF Generator/report.sarif.json does not exist" output.log; then
          echo "SARIF file not found, continuing execution."
        else
          echo "Exiting due to other errors."
          exit 1
        fi

    - name: Pause for Debugging
      if: failure()
      run: sleep 1h
      continue-on-error: true
