name: Black Duck SCA Scan

on:
  workflow_dispatch:

jobs:
  blackduck_scan:
    # runs-on: [ ubuntu-latest ]
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Add Maven to PATH
      run: echo "/home/ubuntu/apps/maven/apache-maven-3.9.8/bin" >> $GITHUB_PATH

    - name: Remove existing Synopsys Bridge
      run: rm -rf /github/home/synopsys-bridge

    - name: Run Synopsys Action for Black Duck
      uses: synopsys-sig/synopsys-action@v1.9.0
      env:
        DETECT_PROJECT_NAME: ${{ github.repository }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.sha }}
        DETECT_TOOLS: 'SIGNATURE_SCAN'
        DETECT_DETECTOR_SEARCH_CONTINUE: 'true'
        DETECT_DETECTOR_SEARCH_DEPTH: '10000'
        DETECT_BLACKDUCK_SIGNATURE_SCANNER_SNIPPET_MATCHING: 'SNIPPET_MATCHING'
        DETECT_BLACKDUCK_SIGNATURE_SCANNER_UPLOAD_SOURCE_MODE: 'true'
      with:
        blackduck_url: ${{ secrets.BLACKDUCK_URL }}
        blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        blackduck_scan_full: true
        blackduck_reports_sarif_create: true
        blackduck_reports_sarif_severities: Critical,High,Medium,Low
        blackduck_upload_sarif_report: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
